language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - mkdir -p build/logs
  - composer install --dev
  - composer require --dev "satooshi/php-coveralls:dev-master"

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
