language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

allow_failures:
  - php: hhvm-nightly

before_script:
  - composer install --dev
  - composer require --dev "satooshi/php-coveralls:dev-master"

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml

script:
  - phpunit --coverage-text --coverage-clover clover.xml
